"use client"

import { Box, Stack } from '@mui/material'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import Sidebar from '@/components/sidebar'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   <Box sx={{display:"flex",alignItems:"flex-start"}}>
    <Sidebar/>
    <Stack direction="column">
      
    <Header/>
    {children}
    </Stack>
   </Box>
  )
}
