"use client";

import React,{useState} from "react"
import { Box, Stack } from "@mui/material";
import type { Metadata } from "next";
// import { Inter } from 'next/font/google'
import Header from "@/components/Header";
import Sidebar from "@/components/sidebar";
import PageHeader from "@/components/PageHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [displayMenuDrawer, setDisplayMenuDrawer] = useState<boolean>(false)
  setDisplayMenuDrawer
  return (
    <Box sx={{ display: "flex", alignItems: "flex-start" }}>
      <Sidebar displayMenuDrawer={displayMenuDrawer} setDisplayMenuDrawer={setDisplayMenuDrawer}/>
      <Stack direction="column" display="flex" width="100%">
        <Header displayMenuDrawer={displayMenuDrawer} handleChangeDisplayMenuDrawer={setDisplayMenuDrawer} />
        <Box width="100%" sx={{padding:"1rem"}}>
          <PageHeader />
          {children}
        </Box>
      </Stack>
    </Box>
  );
}
